apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetshard-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app: fleetshard-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetshard-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fleetshard-sync
    spec:
      serviceAccountName: fleetshard-sync
      containers:
      - name: fleetshard-sync
        image: fleetsync:latest
        imagePullPolicy: Never
        command: 
        - /usr/local/bin/fleetshard-sync
        env:
        - name: OCM_TOKEN
          value: {{ .Values.fleetshardSync.ocmToken }}
        - name: FLEET_MANAGER_ENDPOINT
          value: {{ .Values.fleetshardSync.fleetManagerEndpoint }}
        - name: CLUSTER_ID
          value: {{ .Values.fleetshardSync.clusterId }}
        - name: AUTH_TYPE
          value: {{ .Values.fleetshardSync.authType }}
      {{- if and .Values.fleetshardSync.redHatSSO.clientId .Values.fleetshardSync.redHatSSO.clientSecret (eq .Values.fleetshardSync.authType "RHSSO") }}
        volumeMounts:
          - mountPath: /run/secrets/rhsso
            name: rhsso-token
            readOnly: true
      - name: token-refresher
        image: {{ .Values.fleetshardSync.tokenRefresher.image.name }}:{{ .Values.fleetshardSync.tokenRefresher.image.tag }}
        imagePullPolicy: Always
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: fleetshard-sync-rhsso-creds
                key: clientId
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: fleetshard-sync-rhsso-creds
                key: clientSecret
          - name: ISSUER_URL
            value: https://sso.redhat.com/auth/realms/redhat-external
        command:
          - /bin/token-refresher
          - --oidc.client-id=$(CLIENT_ID)
          - --oidc.client-secret=$(CLIENT_SECRET)
          - --oidc.issuer-url=$(ISSUER_URL)
          - --margin=1m
          - --file=/rhsso/token
        volumeMounts:
          - mountPath: /rhsso
            name: rhsso-token
      volumes:
        - name: rhsso-token
          emptyDir: {}
      {{- end }}
---
{{- if and .Values.fleetshardSync.redHatSSO.clientId .Values.fleetshardSync.redHatSSO.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: fleetshard-sync-rhsso-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app: fleetshard-sync
type: Opaque
stringData:
  clientId: {{ .Values.fleetshardSync.redHatSSO.clientId }}
  clientSecret: {{ .Values.fleetshardSync.redHatSSO.clientSecret }}
---
{{- end }}
