apiVersion: "operators.coreos.com/v1alpha1"
kind: Subscription
metadata:
  name: vertical-pod-autoscaler
  namespace: {{ include "vertical-pod-autoscaler.namespace" . }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vertical-pod-autoscaler
  source: redhat-operators
  sourceNamespace: openshift-marketplace
