# Default values for rhacs-terraform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fleetshardSync:
  authType: ""
  ocmToken: ""
  fleetManagerEndpoint: ""
  clusterId: ""
  redHatSSO:
    clientId: ""
    clientSecret: ""
  tokenRefresher:
    image:
      tag: "latest"
      name: "quay.io/rhoas/mk-token-refresher"
    issuerUrl: "https://sso.redhat.com/auth/realms/redhat-external"
  
acsOperator:
  enabled: false
  startingCSV: rhacs-operator.v3.70.0

# See available parameters in charts/observability/values.yaml
# - enabled flag is used to completely enable/disable observability sub-chart
observability:
  enabled: true
  github:
    accessToken: ""
    repository: ""
  observatorium:
    gateway: ""
    metricsClientId: ""
    metricsSecret: ""
